name: Build APK

on:
  push:
    branches:
      - main  # Убедитесь, что имя ветки соответствует вашей основной ветке
  workflow_dispatch:  # Добавлено для возможности ручного запуска Workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Рекомендуется использовать стабильную версию Python

      - name: Check Buildozer Version
        run: |
          buildozer --version

      - name: Remove build directories (if any)
        run: |
          rm -rf .buildozer/

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk unzip zip wget
          pip install --upgrade pip setuptools cython buildozer python-for-android

      - name: Build APK
        run: |
          buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app.apk
          path: bin/*.apk
