name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up virtual environment
        run: |
          python3 -m venv myenv
          source myenv/bin/activate
          pip install --upgrade pip setuptools cython
          pip install buildozer python-for-android

      - name: Verify Buildozer Installation
        run: |
          source myenv/bin/activate
          buildozer --version

      - name: Build APK
        run: |
          source myenv/bin/activate
          buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app.apk
          path: bin/*.apk
